// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hypmeuqtykuevymutbam.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5cG1ldXF0eWt1ZXZ5bXV0YmFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMjA0NTcsImV4cCI6MjA1OTY5NjQ1N30.ETZFJhX41z_IdSDeawUzK0BQPZcXHP0MmJYVh_MR0o0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);